export const NUTRITION_BAR_WIDTH = 300;
export const NUTRITION_BAR_HEIGHT = 16;
export const NUTRITION_BAR_OFFSET = 30;
export const NUTRITION_BAR_TEXT_OFFSET = 24;
export const NUTRITION_BAR_X_FROM_LEFT = 24;
export const NUTRITION_BAR_Y_FROM_BOTTOM = 24;

export const NUTRITION_BAR_COLOR_OK = 0x00FF00;
export const NUTRITION_BAR_COLOR_WARN = 0xFFFF00;
export const NUTRITION_BAR_COLOR_DANGER = 0xFF0000;
export const NUTRITION_BAR_COLOR_BORDER = 0x000000;
export const NUTRITION_BAR_ALPHA = 0.85;
export const NUTRITION_BAR_INFO_FONT = { font: '14px Arial', fill: '#000' };
